version: '2'
services:
  mongodb:
    image: mongo:3.6.0
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/db/mongo-log.log
    volumes:
      - ./dbdata/:/data/db
      - ./mongod.conf:/etc/mongod.conf
    ports:
        - 27017:27017
    command: mongod --logpath=/data/db/mongo-log.log